In [2]:
import pandas as pd
from datetime import datetime
import re
pd.set_option('display.max_columns', None)

****# **THE CELLS IN THIS NOTEBOOK ARE USED TO FOR EXPLORATORY ANALYSIS AND TO CLEAN UP THE DATA****

In [3]:
df = pd.read_csv('listing.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    object
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
 19  Unnamed: 19           1 non-null      float64
dtypes: float64(10), int64(1), object(9)
memory usage: 154.5+ KB

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [8]:
df['bedrooms'].unique()

array([nan, '1', '2', '5', '3', '4', '8', '6',
       'https://www.airbnb.co.uk/rooms/49009981?adults=1&category_tag=Tag%3A677&children=0&infants=0&search_mode=flex_destinations_search&check_in=2022-04-18&check_out=2022-04-25&previous_page_section_name=1000&federated_search_id=0b044c1c-8d17-4b03-bffb-5de13ff710bc',
       '10', '7'], dtype=object)

In [83]:

df['beds'] = df['beds'].fillna(1)
df['guests'] = df['guests'].fillna(1)
df['bathrooms'] = df['bathrooms'].fillna(1)
df['bedrooms'] = df['bedrooms'].fillna(1)
df[df['beds'].isna()]
# df = df.dropna(subset=['Location_rating'],how='any')
# df

Empty DataFrame
Columns: [ID, Category, Title, Description, Amenities, Location, guests, beds, bathrooms, Price_Night, Cleanliness_rating, Accuracy_rating, Communication_rating, Location_rating, Check-in_rating, Value_rating, amenities_count, url, bedrooms, Unnamed: 19]
Index: []

In [7]:
df['Value_rating'].unique()
df.isna().sum()

ID                        0
Category                  0
Title                     0
Description              88
Amenities                 0
Location                  0
guests                   19
beds                     43
bathrooms               100
Price_Night               0
Cleanliness_rating       98
Accuracy_rating          98
Communication_rating     98
Location_rating          98
Check-in_rating          98
Value_rating             98
amenities_count           0
url                       0
bedrooms                 82
Unnamed: 19             987
dtype: int64

In [17]:
usa_rows = df[df['Category'] == 'Treehouses']

# extract the values in the 'Name' column of the selected rows
usa_names = usa_rows['Value_rating']
usa_names.unique()

array([4.3, 4.5, 4.7, 4.6, nan, 4.4, 4.1, 4.8, 4.9, 5. , 4.2, 4. , 3.3])

In [9]:
import re

df['Description'].str.replace("'About this space',","")
df['Description'] = df['Description'].str.replace('"',"")
df['Description'] = df['Description'].str.replace("' '","")
df['Description'] = df['Description'].str.replace("'","")
df['Description'] = df['Description'].str.replace(r'\\n', '')
df['Description'] = df['Description'].str.replace(r'\\n\\', '')
df['Description'] = df['Description'].str.split(',', n=1).str[-1]
df['Description'] = df['Description'].str[:-2]
df= df.dropna(subset=['Description'])


# remove about this plce
df['Description'][5]

' Charming cabin nestled in the leaves, real unusual and cozy house in the trees with all the modern comforts, just 45 minutes from Paris, 28 km from Disneyland or Provins and 5 minutes from the Parc des F√©lins. This cozy nest awaits you year-round for an unusual romantic or family experience. A parenthesis of relaxation and relaxation, ideal to offer yourself or yourself. See you soon :), The space, The space\\nLa Cabane Perch√©e de Chambonni√®re awaits you over the seasons and offers a comfortable and cozy setting amidst the trees, the opportunity to escape from everyday life during a romantic stay with two or family, for one or more nights.\\n\\nYou will be seduced by this treehouse full of charm with neat decoration.\\n- Access by gentle slope, ideal for welcoming you easily.\\n- Charming living room with bioethanol fireplace (only in cold weather and exclusively for couples or families with children over 7 years old)\\n- Fully equipped kitchen.\\n- Double bedroom + 1 bedroom with 2 single beds upstairs\\n- Shower room with shower and real toilet\\n- Magnificent private terrace of 36m¬≤ with garden furniture and deckchair.\\n\\n\\nThis cozy nest in the trees offers all the modern comforts (electricity, heating, bathroom with toilet and standard shower, flat screen TV, and a kitchenette with multifunction oven, refrigerator, hob, wifi internet access...). For your arrival, all beds are made.\\n\\nThe shack perched in chambonni√®re is ideally located to allow you to discover the charms of the Seine and Marne and the Champagne region:\\n> the Parc des F√©lins,\\n> the medieval city of Provins with magnificent equestrian and falconry shows in season,\\n> Disneyland Paris & La Vall√©e Village 25mn,\\n> the castles of Vaux le Vicomte, Blandy les Tours and Fontainebleau\\n> and for the most sporty (depending on the season):\\n- tree climbing,\\n- paintball,\\n- karting and other motor sports.\\n> Youll also have a chance to go for nice walks around on foot or by mountain bike and tennis in the village.\\n\\nA parenthesis of relaxation and relaxation, ideal to offer yourself or yourself .\\n\\nLooking forward to welcoming you‚Ä¶\\n\\n\\nThe rates shown in the calendar are for 2 people. Rates for 4 people are calculated automatically when booking\\n\\nA surcharge may be charged if the general condition rendered is indecent., Other things to note, Other things to note\\nThe owners reserve the right to cancel your stay at the hut if the weather conditions are very bad, whether they are known a few days before, or even on the day of arrival, whether you are already on the road or already arrived on site, or during your stay (weather alert, severe weather events, strong wind, storm, thunderstorm). If this happens, well try to relocate you to other types of accommodation nearby, subject to availability and at no extra charge. If we do not have a relocation solution available, and in this case only, you will be offered a date extension at the choice of the owners or you will receive a 50% discount on a next equivalent stay in a cabin in the current 12 months. In any case, no compensation or reimbursement can be claimed'

In [72]:
df['Description'][9]

' Our lodges are pretty eco-chalets equipped with 2 bedrooms, bathroom, kitchen and living room. Their covered terrace will allow you to make the most of breakfast or aperitif because the luxury here is space and nature !For a week or more, treat yourself to a breath of fresh air in this nature hotel, unique in southern Brittany!, The space, The spaceDihan (break in Breton) is a very natural cocktail of history, unusual,travel, and love of Brittany.A few kilometers from the sea, between Carnac and Quiberon peninsula, thisoriginal structure, the first unusual European ecolabel site, precursor of nights in huts in the trees is an ecolodge born from the old family farm.Since then, many unusual accommodations have gradually nestled on our 25-hectare estate in Ploemel.Treehouses, yurts, hobbit houses... Get ready for an out-of-time experience, where vegetation is king ! Here, you can light up with a candle and a dynamo lamp and forget about your mobile phone...With a space dedicated to relaxation, enjoy our hamman, sauna and massages from around the world.On the catering side, breakfasts are served in baskets and hoisted in huts perched thanks to a system of pulleys. In the evening, meal baskets are available, upon reservation. For a friendly moment with family or friends, head to the Caf√© Lounge area located on the terrace of our wooden pool and enjoy our snacks made in Breizh products'